# Generated by Django 2.0.7 on 2018-07-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=1, upload_to='movie_images'),
            preserve_default=False,
        ),
    ]
